/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gerbook_regbook_MyNDK */

#ifndef _Included_com_gerbook_regbook_MyNDK
#define _Included_com_gerbook_regbook_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gerbook_regbook_MyNDK
 * Method:    getStat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_gerbook_regbook_MyNDK_getStat
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
